// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {time} from '../models';

export function BlockWebsite(arg1:string):Promise<string>;

export function DisableCommandPrompt():Promise<string>;

export function DisableFileDownloads():Promise<string>;

export function DisableWindowsUpdates():Promise<string>;

export function GetContext():Promise<context.Context>;

export function Greet(arg1:string):Promise<string>;

export function SetLockScreenTimeout(arg1:time.Duration):Promise<string>;
