// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockWebsite(arg1) {
  return window['go']['main']['App']['BlockWebsite'](arg1);
}

export function DisableCommandPrompt() {
  return window['go']['main']['App']['DisableCommandPrompt']();
}

export function DisableFileDownloads() {
  return window['go']['main']['App']['DisableFileDownloads']();
}

export function DisableWindowsUpdates() {
  return window['go']['main']['App']['DisableWindowsUpdates']();
}

export function GetContext() {
  return window['go']['main']['App']['GetContext']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetLockScreenTimeout(arg1) {
  return window['go']['main']['App']['SetLockScreenTimeout'](arg1);
}
